# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestOutback():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_outback(self):

    self.driver.find_element(By.CSS_SELECTOR, ".ant-select-focused .ant-select-selection__placeholder").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-select-dropdown-menu-item-active").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-btn:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-layout-sider-children").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-layout-sider-children").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".tradeWalkInfoContainer___2fgX-")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".tradeWalkInfoContainer___2fgX-")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".tradeWalkInfoContainer___2fgX-")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".tradeWalkInfoContainer___2fgX-")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".tradeWalkInfoContainer___2fgX-")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".tradeWalkInfoContainer___2fgX-")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .doubletButton___3Cqkd > .ant-btn:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > .doubletButton___3Cqkd > .ant-btn:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) .ant-btn:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nextButtonWrap___2pLip > .ant-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".doubletButton___3Cqkd > .ant-btn-default:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".duplicate___UyrI7").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-layout-sider-children").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input-search > .ant-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input-search > .ant-input").send_keys("4S4BSAKC4J3249705")
    self.driver.find_element(By.CSS_SELECTOR, ".highlighted___2pqMl").click()
  
